# Generated by Django 5.1.2 on 2025-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('end_year', models.IntegerField()),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='piece_images')),
                ('price', models.FloatField(blank=True, null=True)),
                ('pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('replacement_cost', models.FloatField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(to='creators.artist')),
                ('shows', models.ManyToManyField(to='events.show')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
